### ISSUE TITLE
Channel with multiple live streams gives error

### ISSUE THREAD

**Issue by nasircsms** [abskmj/youtube-hls-m3u8#17]
Works for any channel with one live stream.. but gives following error when there are multiple live streams

`Error: Stream not found for Youtube URL: https://www.youtube.com/channel/UCMmpLL2ucRHAXbNHiCPyIyg/live<br> &nbsp; &nbsp;at getLiveStream (/home/vagrant/setup-apps/scrappers/youtube-iptv-channels/src/app.js:30:15)<br> &nbsp; &nbsp;at process.processTicksAndRejections (node:internal/process/task_queues:95:5)<br> &nbsp; &nbsp;at async /home/vagrant/setup-apps/scrappers/youtube-iptv-channels/src/app.js:73:30`

**Comment by abskmj** [comment]
A change on YouTube has broken this functionality. Looking for an alternative way. Meanwhile, you can use the video id for streaming.

**Comment by LivreAcessoPro** [comment]
Look at https://streamlink.github.io/
